//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace XPC.Web {
    
    
    public partial class Default {
        
        /// <summary>
        /// HomeBonBaiNoiBat control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XPC.Web.GUI.HomeBonBaiNoiBat HomeBonBaiNoiBat;
        
        /// <summary>
        /// TinDocNhieu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XPC.Web.GUI.HomeTinDocNhieu TinDocNhieu;
        
        /// <summary>
        /// HomeVideo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XPC.Web.GUI.HomeVideo HomeVideo;
        
        /// <summary>
        /// HomeNoiBatHorizal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XPC.Web.GUI.HomeNoiBatHorizal HomeNoiBatHorizal;
        
        /// <summary>
        /// HomeAnhDep control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XPC.Web.GUI.HomeAnhDep HomeAnhDep;
        
        /// <summary>
        /// HomeNoiBatHorizal1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XPC.Web.GUI.HomeNoiBatHorizal HomeNoiBatHorizal1;
        
        /// <summary>
        /// HomeAnhDep1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XPC.Web.GUI.HomeAnhDep HomeAnhDep1;
        
        /// <summary>
        /// HomeNoiBatVertical control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XPC.Web.GUI.HomeNoiBatVertical HomeNoiBatVertical;
        
        /// <summary>
        /// HomeNoiBatVertical1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XPC.Web.GUI.HomeNoiBatVertical HomeNoiBatVertical1;
        
        /// <summary>
        /// HomeVote control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XPC.Web.GUI.HomeVote HomeVote;
        
        /// <summary>
        /// HomeNoiBatHorizal2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XPC.Web.GUI.HomeNoiBatHorizal HomeNoiBatHorizal2;
        
        /// <summary>
        /// HomeNoiBatHorizal3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::XPC.Web.GUI.HomeNoiBatHorizal HomeNoiBatHorizal3;
    }
}
