//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portal.GUI.EditoralOffice.MainOffce.Media {
    
    public partial class AlbumImages {
        protected System.Web.UI.WebControls.ImageButton UpBtn;
        protected System.Web.UI.WebControls.ImageButton GoRoot;
        protected System.Web.UI.WebControls.TextBox txtNewFolder;
        protected System.Web.UI.WebControls.Button btnCreateNewFolder;
        protected System.Web.UI.WebControls.DropDownList cbxViewBy;
        protected System.Web.UI.WebControls.GridView grdListImage;
        protected System.Web.UI.WebControls.GridView GridView1;
        protected System.Web.UI.WebControls.LinkButton LinkDelete;
        protected System.Web.UI.WebControls.TextBox txtKeyword;
        protected System.Web.UI.WebControls.Button btnSearch;
        protected System.Web.UI.HtmlControls.HtmlInputFile file2;
        protected System.Web.UI.HtmlControls.HtmlInputFile file3;
        protected System.Web.UI.HtmlControls.HtmlInputFile file4;
        protected System.Web.UI.HtmlControls.HtmlInputFile file1;
        protected System.Web.UI.HtmlControls.HtmlInputFile file5;
        protected System.Web.UI.WebControls.Button btnSave;
        protected System.Web.UI.HtmlControls.HtmlInputButton btnBack;
        protected System.Web.UI.WebControls.Label lblFileError;
        protected DFISYS.GUI.Editoral.Gallery.UserControl.ctlPopupView CtlPopupView2;
        protected DFISYS.GUI.Editoral.Gallery.UserControl.cltPopupMedia CltPopupMedia1;
        protected Portal.GUI.Editoral.Gallery.UserControl.cltPopupFlash cltPopupFlash1;
    }
}
